language: php
sudo: false
php:
- 5.3
- 5.4
- 5.5
- 5.6
- hhvm
matrix:
  allow_failures:
  - php: 5.3
  - php: 5.6
  - php: hhvm
env:
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.1.0
  - MAGENTO_VERSION=magento-ce-1.8.1.0
  - MAGENTO_VERSION=magento-ce-1.7.0.2
  global:
    secure: hf9lSZ6rvuYJvaxvsMOM0QSd+cPWydZK3Sft41UR/LLL/LOPCsWUbIQ2a4gPbtJenaqtZft89oc7aa2MpiR9EvpwAckXrBtL+xkcaiSbLhf2mEGmsc09nQR2hS3SvraaI6qT5qHoVblJ3asjnRl0w6QxuOhWKqbJlDdglSQY6wk=
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/testing/setup.sh
  | bash
notifications:
  slack:
    secure: juDTf7Vs8gjhFPB2CR0/6iBJS7etrf610kIxFh1JU9DNEqdJ47pJubrrcAYeq8eRP1oZYTq9NHCoOAap+KFF0jssQcbW0/i0mLV7p19jj7KVMqNH1IHrA31fjgFGyPcyouczyjBjPVe6ADcpgSr3uqz/+SRTs5hJPEwdskw5Zls=
